cc_binary(
    name = "mycc",
    srcs = [
        "main.c",
        "parser.c",
        "parser.h",
        "tokenizer.c",
        "tokenizer.h",
        "util.c",
        "util.h",
        "assembler.c",
        "assembler.h",
    ],
    copts = ["-std=c11 -g -static"]
)